modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/UltrusBot/SizeShiftingPotions/issues"

[[mods]]
modId="sizeshiftingpotions"
version="${version}"
displayName="Size Shifting Potions"
logoFile="icon.png"
authors="UltrusBot"
description='''
Adds shrinking and growing potions to the game!
'''
[[dependencies.sizeshiftingpotions]]
modId="forge"
mandatory=true
versionRange="[38,)"
ordering="NONE"
side="BOTH"
[[dependencies.sizeshiftingpotions]]
modId="minecraft"
mandatory=true
versionRange="[1.20,)"
ordering="NONE"
side="BOTH"
[[dependencies.sizeshiftingpotions]]
modId="midnightlib"
mandatory=true
versionRange="[1.4.1,)"
ordering="NONE"
side="BOTH"